AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  CacheRootDirectory: tmp/rubocop_cache

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
