module Immuto
  VERSION: String

  class Error < StandardError
  end

  class UnknownAttributeError < Error
    def initialize: (untyped attribute) -> void
  end

  class MissingAttributeError < Error
    def initialize: (untyped attribute) -> void
  end

  class NestedUpdateError < Error
    def initialize: (untyped attribute) -> void
  end

  class ValidationError < Error
    def initialize: (untyped attribute, ?String? message) -> void
  end

  class Attribute
    attr_reader name: Symbol

    def initialize: (name: String | Symbol, ?default: untyped, ?validator: untyped, ?message: String?) -> void
    def default?: () -> bool
    def default_value: () -> untyped
    def validate: (untyped value) -> nil
    def ==: (untyped other) -> bool
    def eql?: (untyped other) -> bool
    def hash: () -> Integer
  end

  module Immutable
    def with: (**untyped changes) -> instance
    def with_path: (*untyped path_and_value) -> instance
    def to_h: () -> Hash[Symbol, untyped]
    def to_json: (*untyped args) -> String
    def ==: (untyped other) -> bool
    def eql?: (untyped other) -> bool
    def hash: () -> Integer
    def inspect: () -> String

    module ClassMethods
      def attribute: (String | Symbol name, ?default: untyped, ?validate: untyped, ?message: String?) -> Immuto::Attribute
      def attributes: () -> Array[Immuto::Attribute]
      def from_h: (untyped attributes) -> untyped
      def attribute_names: () -> Array[Symbol]
    end
  end
end
